### ISSUE TITLE
installer problem

### ISSUE THREAD

**Issue by carande** [andycasey/moog#2]
Hi, I've been trying to use your installers to set up moog - thanks a lot for making them!  I am attempting the build on an intel macbook pro, OSX 10.6.8.  I've tried using both the included python script (setup.py) as well as pip, and both attempts fail with similar errors:
...
ld: symbol(s) not found for architecture x86_64
...
make: **\* [MOOG] Error 1
...
error: file '/private/tmp/pip-build-root/moog/moog/MOOG' does not exist

EDIT:: Apparently the problem had to do with my gfortran compiler being in 64bit mode.  I got g77 and it compiled correctly.  Problem solved!
